---

- hosts: all
  become: true
  pre_tasks:

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_server
  become: true
  tasks:

  - name: Install Message Queue and Memcached
    apt:
      name:
        - rabbitmq-server
        - memcached
      state: latest
      update_cache: yes
