---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: Install nova (Unbuntu)
    apt:
      name:
        - nova-compute
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
