---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

  - name: install prometheus (Ubuntu)
    apt:
      name:
        - prometheus
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install prometheus (CentOS)
    command: snap install prometheus --classic
    when: ansible_distribution == "CentOS"

